### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by captdeys** [recoilphp/react#11]
Problem 1
    - recoil/react[1.0.0-alpha.1, ..., 1.0.2] require php ^7 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by jmalloc** [comment]
Thanks for the report, I will look into as soon as possible.

**Comment by jmalloc** [comment]
- [x] Blocked by https://github.com/eloquent/phony/issues/250
- [x] Blocked by https://github.com/recoilphp/api/issues/11
- [x] Blocked by https://github.com/recoilphp/kernel/issues/8
- [x] Blocked by https://github.com/recoilphp/dev/issues/20

**Comment by captdeys** [comment]
Thank you for taking a look at this so quickly

**Comment by jmalloc** [comment]
I have made some limited progress towards this. A lot of the Recoil dev dependencies do not yet support PHP 8.0, even though I suspect Recoil itself will work just fine.

In recoilphp/api#11 I ended up converting porting the tests to PHPUnit as the test & expectation frameworks I *was* using seem to be slow moving or even abandoned. That was a relatively small test suite; the other repos will likely take me somewhat longer.

**Comment by bitpetr** [comment]
Is this still blocked?

**Comment by jmalloc** [comment]
> Is this still blocked?

It is, sorry. I haven't had a chance to allocate much time to this recently.

As mentioned above, the hold up is related to the testing tools I'm using themselves not working under PHP 8 so I've decided to migrate the tests back to PHPUnit which does cause some problems because the system I was using (peridot) allowed me write a plugin which ran Recoil coroutines as tests, something I haven't worked out how to do with PHPUnit.

That said, I am fairly confident there should not be any real problems under PHP 8, so I will make an attempt to relax the composer constraint and at least tag a pre-release version for everyone to try.

Thanks for your patience.

**Comment by jmalloc** [comment]
`recoil/react` should at least be installable now using the `dev-php-8` constraint. I would appreciate any feedback about problems under PHP 8 as I work towards migrating the tests so I can be confident in saying it is properly supported.

**Comment by bitpetr** [comment]
Thanks.
I'm using 1.0.2 with PHP 8.0.1 in my small project without any visible issues.

**Comment by captdeys** [comment]
Good to hear that it seems to be working. I've had to downgrade my php version anyways due to some other issues as well. I might be able to give this update a try soon.

**Comment by myehiz** [comment]
Delete the composer.lock file and run composer install. Worked like magic for me.

**Comment by jmalloc** [comment]
This has (finally) been fixed properly in [v1.0.3](https://github.com/recoilphp/react/releases/tag/1.0.3), thank you for your patience.
